name: PR Comment Word Limit Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR comment word count
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || "";
            const wordCount = prBody.trim().split(/\s+/).filter(word => word.length > 0).length;

            console.log(`PR description word count: ${wordCount}`);

            if (wordCount > 10) {
              core.setFailed(`❌ Pull request description contains ${wordCount} words. Limit is 10.`);
            } else {
              console.log(`✅ Pull request description is within the allowed limit.`);
            }
